[theme]
base="light"
secondaryBackgroundColor="#b9b9b9"
textColor="#000000"
font="monospace"

[server]
headless = true
enableXsrfProtection = false
enableCORS = false
port = 8080
maxUploadSize = 500
maxMessageSize = 500
